version = 0.1

[default.deploy.parameters]
stack_name = "db-less-rag-demo"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
parameter_overrides = "LLMProvider=bedrock LLMModel=amazon.nova-lite-v1:0"

[default.build.parameters]
cached = true
parallel = true
