#!/usr/bin/env bash
set -euo pipefail

stack_name="${1:-${SAM_STACK_NAME:-db-less-rag-demo}}"
config_path="frontend/config.js"

api_url="$(aws cloudformation describe-stacks \
  --stack-name "$stack_name" \
  --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue | [0]" \
  --output text)"

if [[ -z "$api_url" || "$api_url" == "None" ]]; then
  echo "Could not find the ApiUrl output for CloudFormation stack: $stack_name" >&2
  exit 1
fi

if [[ "$api_url" != https://* ]]; then
  echo "The ApiUrl output is not an HTTPS URL: $api_url" >&2
  exit 1
fi

mkdir -p "$(dirname "$config_path")"
temporary_path="$(mktemp "${TMPDIR:-/tmp}/tracerag-config.XXXXXX")"
trap 'rm -f "$temporary_path"' EXIT

api_url_json="$(printf '%s' "$api_url" | python3 -c 'import json, sys; print(json.dumps(sys.stdin.read()))')"
{
  echo "// Generated by scripts/update-frontend-config.sh. Do not edit by hand."
  echo "window.APP_CONFIG = {"
  printf '  apiUrl: %s,\n' "$api_url_json"
  echo "};"
} > "$temporary_path"

mv "$temporary_path" "$config_path"
trap - EXIT
echo "Updated $config_path from stack $stack_name ($api_url)"
